<template><div><h1 id="about" tabindex="-1"><a class="header-anchor" href="#about"><span>About</span></a></h1>
<p>The <strong>meltwater contribution</strong> from snow and ice in mountainous regions plays a critical role in <strong>sustaining life downstream</strong>, supporting potable water security, agriculture, industry, hydropower generation and mining, especially in the current regime of climate change.</p>
<h2 id="overall-objective" tabindex="-1"><a class="header-anchor" href="#overall-objective"><span>Overall Objective</span></a></h2>
<p>To effectively address this challenge, <strong>SNOWCOP leverages the full potential of the European Union Copernicus data and infrastructure</strong> to provide novel <strong>snow water equivalent (SWE) and ice melting rate maps with high spatio-temporal resolution</strong>, suitable to monitor meltwater dynamics in complex mountainous terrains.</p>
<p><img src="/images/overall.png" alt="overview"></p>
<h2 id="methodology" tabindex="-1"><a class="header-anchor" href="#methodology"><span>Methodology</span></a></h2>
<p>Cutting-edge methods will be employed to extract <strong>valuable information about snow and glacier from satellite data</strong>, which will then be <strong>assimilated into a physically based model for snow and ice water equivalent estimation</strong>. The model will be run in a hindcast mode, generating reanalysis data spanning <strong>the past 20+ years at daily resolution</strong>. Notably, the proposed approach yields SWE maps over a <strong>50-m pixel size</strong>, achieving an unprecedented level of spatial detail for the vast area of the extra-tropical Andes Cordillera.</p>
<p><img src="/images/MRI_pre_results.png" alt="MRI_pre_results"></p>
<h2 id="cdse" tabindex="-1"><a class="header-anchor" href="#cdse"><span>CDSE</span></a></h2>
<p>The <a href="https://dataspace.copernicus.eu/" target="_blank" rel="noopener noreferrer">Copernicus Data Space Ecosystem (CDSE)</a> infrastructure, which houses both processing facilities and a comprehensive data repository, serves as the backbone for this project. <strong>CDSE will be populated with all the necessary codes, in-situ data, and third-party space data, enabling the seamless extraction, processing, and analysis of mountain cryosphere-related information</strong>. To further enhance accessibility and utilization, a user-friendly and standardized API and a robust dissemination strategy will be implemented in collaboration with key public authorities in Europe and South America. This strategic approach aims to <strong>attract new users from both the scientific and commercial sectors</strong>, ensuring that the project’s valuable data and insights reach a broad audience.</p>
<h2 id="egnss-snow-stations" tabindex="-1"><a class="header-anchor" href="#egnss-snow-stations"><span>EGNSS snow stations</span></a></h2>
<p>SNOWCOP will leverage innovative <strong>snow stations powered by EGNSS technology</strong> to reinforce in-situ measurements of SWE and liquid water content (LWC). These stations will be positioned on locations that <strong>optimally represent the snowmelt dynamics within a specific catchment</strong> based on the project generated reanalysis data.</p>
<p><img src="/images/egnss_station.png" alt="egnss"></p>
<h2 id="impacts" tabindex="-1"><a class="header-anchor" href="#impacts"><span>Impacts</span></a></h2>
<p>Focusing on the critical Andes Mountain range, where meltwater serves as a vital lifeline for millions of people but remains poorly monitored, this initiative <strong>leverages the expertise of the International Copernicus partners at the University of Chile</strong>. Through this collaboration, we tackle shared challenges faced by mountain regions globally, <strong>developing replicable solutions that unlock new opportunities for both local and European communities</strong>.</p>
</div></template>


